version: '3.5'
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: jupyter
    tty: true
    restart: always
    ports:
      - 8888:8888
    volumes:
      - ./ssh:/home/user/.ssh
      - ./work:/home/user/work
    entrypoint : >
      jupyter-lab
      --ip=0.0.0.0
      --no-browser
      --NotebookApp.token=''
#    command: chmod -R 700 /home/user/.ssh
